#include "gmock/gmock.h"
#include "gtest/gtest.h"
#include "ScalarVariable.h"
using ::testing::Return;

namespace UnitTests
{
	TEST(ScalarVariableTests, WhenCreatingScalar_ThenCorrectTypeChosen)
	{
		ASSERT_EQ(ScalarVariable(static_cast<uint8_t>(0)).Type, UINT8);
		ASSERT_EQ(ScalarVariable(static_cast<uint16_t>(0)).Type, UINT16);
		ASSERT_EQ(ScalarVariable(static_cast<uint32_t>(0)).Type, UINT32);
		ASSERT_EQ(ScalarVariable(static_cast<uint64_t>(0)).Type, UINT64);
		ASSERT_EQ(ScalarVariable(static_cast<int8_t>(0)).Type, INT8);
		ASSERT_EQ(ScalarVariable(static_cast<int16_t>(0)).Type, INT16);
		ASSERT_EQ(ScalarVariable(static_cast<int32_t>(0)).Type, INT32);
		ASSERT_EQ(ScalarVariable(static_cast<int64_t>(0)).Type, INT64);
		ASSERT_EQ(ScalarVariable(static_cast<float>(0)).Type, FLOAT);
		ASSERT_EQ(ScalarVariable(static_cast<double>(0)).Type, DOUBLE);
		ASSERT_EQ(ScalarVariable::FromTick(static_cast<uint32_t>(0)).Type, TICK);
	}
	TEST(ScalarVariableTests, WhenCastingScalar_ThenCorrectValueReturned)
	{
		ASSERT_EQ(ScalarVariable(static_cast<uint8_t>(10)).To<uint8_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint8_t>(10)).To<uint16_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint8_t>(10)).To<uint32_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint8_t>(10)).To<uint64_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint8_t>(10)).To<int8_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint8_t>(10)).To<int16_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint8_t>(10)).To<int32_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint8_t>(10)).To<int64_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint8_t>(10)).To<float>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint8_t>(10)).To<double>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint16_t>(10)).To<uint8_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint16_t>(10)).To<uint16_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint16_t>(10)).To<uint32_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint16_t>(10)).To<uint64_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint16_t>(10)).To<int8_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint16_t>(10)).To<int16_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint16_t>(10)).To<int32_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint16_t>(10)).To<int64_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint16_t>(10)).To<float>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint16_t>(10)).To<double>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint32_t>(10)).To<uint8_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint32_t>(10)).To<uint16_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint32_t>(10)).To<uint32_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint32_t>(10)).To<uint64_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint32_t>(10)).To<int8_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint32_t>(10)).To<int16_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint32_t>(10)).To<int32_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint32_t>(10)).To<int64_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint32_t>(10)).To<float>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint32_t>(10)).To<double>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint64_t>(10)).To<uint8_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint64_t>(10)).To<uint16_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint64_t>(10)).To<uint32_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint64_t>(10)).To<uint64_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint64_t>(10)).To<int8_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint64_t>(10)).To<int16_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint64_t>(10)).To<int32_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint64_t>(10)).To<int64_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint64_t>(10)).To<float>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<uint64_t>(10)).To<double>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int8_t>(10)).To<uint8_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int8_t>(10)).To<uint16_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int8_t>(10)).To<uint32_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int8_t>(10)).To<uint64_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int8_t>(10)).To<int8_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int8_t>(10)).To<int16_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int8_t>(10)).To<int32_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int8_t>(10)).To<int64_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int8_t>(10)).To<float>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int8_t>(10)).To<double>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int16_t>(10)).To<uint8_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int16_t>(10)).To<uint16_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int16_t>(10)).To<uint32_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int16_t>(10)).To<uint64_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int16_t>(10)).To<int8_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int16_t>(10)).To<int16_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int16_t>(10)).To<int32_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int16_t>(10)).To<int64_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int16_t>(10)).To<float>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int16_t>(10)).To<double>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int32_t>(10)).To<uint8_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int32_t>(10)).To<uint16_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int32_t>(10)).To<uint32_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int32_t>(10)).To<uint64_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int32_t>(10)).To<int8_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int32_t>(10)).To<int16_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int32_t>(10)).To<int32_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int32_t>(10)).To<int64_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int32_t>(10)).To<float>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int32_t>(10)).To<double>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int64_t>(10)).To<uint8_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int64_t>(10)).To<uint16_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int64_t>(10)).To<uint32_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int64_t>(10)).To<uint64_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int64_t>(10)).To<int8_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int64_t>(10)).To<int16_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int64_t>(10)).To<int32_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int64_t>(10)).To<int64_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int64_t>(10)).To<float>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<int64_t>(10)).To<double>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<float>(10)).To<uint8_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<float>(10)).To<uint16_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<float>(10)).To<uint32_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<float>(10)).To<uint64_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<float>(10)).To<int8_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<float>(10)).To<int16_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<float>(10)).To<int32_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<float>(10)).To<int64_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<float>(10)).To<float>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<float>(10)).To<double>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<double>(10)).To<uint8_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<double>(10)).To<uint16_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<double>(10)).To<uint32_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<double>(10)).To<uint64_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<double>(10)).To<int8_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<double>(10)).To<int16_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<double>(10)).To<int32_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<double>(10)).To<int64_t>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<double>(10)).To<float>(), 10);
		ASSERT_EQ(ScalarVariable(static_cast<double>(10)).To<double>(), 10);
		ASSERT_EQ(ScalarVariable::FromTick(static_cast<uint32_t>(10)).To<uint8_t>(), 10);
		ASSERT_EQ(ScalarVariable::FromTick(static_cast<uint32_t>(10)).To<uint16_t>(), 10);
		ASSERT_EQ(ScalarVariable::FromTick(static_cast<uint32_t>(10)).To<uint32_t>(), 10);
		ASSERT_EQ(ScalarVariable::FromTick(static_cast<uint32_t>(10)).To<uint64_t>(), 10);
		ASSERT_EQ(ScalarVariable::FromTick(static_cast<uint32_t>(10)).To<int8_t>(), 10);
		ASSERT_EQ(ScalarVariable::FromTick(static_cast<uint32_t>(10)).To<int16_t>(), 10);
		ASSERT_EQ(ScalarVariable::FromTick(static_cast<uint32_t>(10)).To<int32_t>(), 10);
		ASSERT_EQ(ScalarVariable::FromTick(static_cast<uint32_t>(10)).To<int64_t>(), 10);
		ASSERT_EQ(ScalarVariable::FromTick(static_cast<uint32_t>(10)).To<float>(), 10);
		ASSERT_EQ(ScalarVariable::FromTick(static_cast<uint32_t>(10)).To<double>(), 10);
	}

	TEST(ScalarVariableTests, WhenAddingScalar_ThenCorrectValueReturned)
	{
		ScalarVariable result;
		
		result = ScalarVariable(static_cast<uint8_t>(10)) + ScalarVariable(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result.To<uint8_t>(), 20);
		result = ScalarVariable(static_cast<uint8_t>(10)) + ScalarVariable(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result.To<uint8_t>(), 20);
		result = ScalarVariable(static_cast<uint8_t>(10)) + ScalarVariable(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result.To<uint8_t>(), 20);
		result = ScalarVariable(static_cast<uint8_t>(10)) + ScalarVariable(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result.To<uint8_t>(), 20);
		result = ScalarVariable(static_cast<uint8_t>(10)) + ScalarVariable(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result.To<uint8_t>(), 20);
		result = ScalarVariable(static_cast<uint8_t>(10)) + ScalarVariable(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result.To<uint8_t>(), 20);
		result = ScalarVariable(static_cast<uint8_t>(10)) + ScalarVariable(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result.To<uint8_t>(), 20);
		result = ScalarVariable(static_cast<uint8_t>(10)) + ScalarVariable(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result.To<int8_t>(), 20);
		result = ScalarVariable(static_cast<uint8_t>(10)) + ScalarVariable(static_cast<int8_t>(-20));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), -10);
		result = ScalarVariable(static_cast<uint8_t>(10)) + ScalarVariable(static_cast<int16_t>(-20));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), -10);
		result = ScalarVariable(static_cast<uint8_t>(10)) + ScalarVariable(static_cast<int32_t>(-20));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), -10);
		result = ScalarVariable(static_cast<uint8_t>(10)) + ScalarVariable(static_cast<int64_t>(-20));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), -10);
		result = ScalarVariable(static_cast<uint8_t>(10)) + ScalarVariable(static_cast<int64_t>(-139));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), -129);
		result = ScalarVariable(static_cast<uint8_t>(10)) + ScalarVariable(static_cast<int64_t>(-32779));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -32769);
		result = ScalarVariable(static_cast<uint8_t>(10)) + ScalarVariable(-static_cast<int64_t>(2147483659));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -static_cast<int64_t>(2147483649));
		result = ScalarVariable(static_cast<uint8_t>(10)) + ScalarVariable(static_cast<uint8_t>(250));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result.To<uint16_t>(), 260);
		result = ScalarVariable(static_cast<uint8_t>(10)) + ScalarVariable(static_cast<uint16_t>(65534));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result.To<uint32_t>(), 65544);
		result = ScalarVariable(static_cast<uint8_t>(10)) + ScalarVariable(static_cast<uint32_t>(4294967294));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result.To<uint64_t>(), 4294967304);
		result = ScalarVariable(static_cast<uint8_t>(10)) + ScalarVariable(static_cast<float>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = ScalarVariable(static_cast<uint8_t>(10)) + ScalarVariable(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		result = ScalarVariable(static_cast<uint8_t>(10)) + ScalarVariable::FromTick(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, TICK);
		ASSERT_EQ(result.To<uint32_t>(), 20);
		
		result = ScalarVariable(static_cast<uint16_t>(10)) + ScalarVariable(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result.To<uint16_t>(), 20);
		result = ScalarVariable(static_cast<uint16_t>(10)) + ScalarVariable(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result.To<uint16_t>(), 20);
		result = ScalarVariable(static_cast<uint16_t>(10)) + ScalarVariable(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result.To<uint16_t>(), 20);
		result = ScalarVariable(static_cast<uint16_t>(10)) + ScalarVariable(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result.To<uint16_t>(), 20);
		result = ScalarVariable(static_cast<uint16_t>(10)) + ScalarVariable(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result.To<uint16_t>(), 20);
		result = ScalarVariable(static_cast<uint16_t>(10)) + ScalarVariable(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result.To<uint16_t>(), 20);
		result = ScalarVariable(static_cast<uint16_t>(10)) + ScalarVariable(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result.To<uint16_t>(), 20);
		result = ScalarVariable(static_cast<uint16_t>(10)) + ScalarVariable(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result.To<uint16_t>(), 20);
		result = ScalarVariable(static_cast<uint16_t>(10)) + ScalarVariable(static_cast<int8_t>(-20));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), -10);
		result = ScalarVariable(static_cast<uint16_t>(10)) + ScalarVariable(static_cast<int16_t>(-20));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), -10);
		result = ScalarVariable(static_cast<uint16_t>(10)) + ScalarVariable(static_cast<int32_t>(-20));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), -10);
		result = ScalarVariable(static_cast<uint16_t>(10)) + ScalarVariable(static_cast<int64_t>(-20));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), -10);
		result = ScalarVariable(static_cast<uint16_t>(10)) + ScalarVariable(static_cast<int64_t>(-139));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), -129);
		result = ScalarVariable(static_cast<uint16_t>(10)) + ScalarVariable(static_cast<int64_t>(-32779));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -32769);
		result = ScalarVariable(static_cast<uint16_t>(10)) + ScalarVariable(-static_cast<int64_t>(2147483659));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -static_cast<int64_t>(2147483649));
		result = ScalarVariable(static_cast<uint16_t>(10)) + ScalarVariable(static_cast<uint8_t>(250));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result.To<uint16_t>(), 260);
		result = ScalarVariable(static_cast<uint16_t>(10)) + ScalarVariable(static_cast<uint16_t>(65534));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result.To<uint32_t>(), 65544);
		result = ScalarVariable(static_cast<uint16_t>(10)) + ScalarVariable(static_cast<uint32_t>(4294967294));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result.To<uint64_t>(), 4294967304);
		result = ScalarVariable(static_cast<uint16_t>(10)) + ScalarVariable(static_cast<float>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = ScalarVariable(static_cast<uint16_t>(10)) + ScalarVariable(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		result = ScalarVariable(static_cast<uint16_t>(10)) + ScalarVariable::FromTick(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, TICK);
		ASSERT_EQ(result.To<uint32_t>(), 20);
		
		result = ScalarVariable(static_cast<uint32_t>(10)) + ScalarVariable(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result.To<uint32_t>(), 20);
		result = ScalarVariable(static_cast<uint32_t>(10)) + ScalarVariable(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result.To<uint32_t>(), 20);
		result = ScalarVariable(static_cast<uint32_t>(10)) + ScalarVariable(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result.To<uint32_t>(), 20);
		result = ScalarVariable(static_cast<uint32_t>(10)) + ScalarVariable(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result.To<uint32_t>(), 20);
		result = ScalarVariable(static_cast<uint32_t>(10)) + ScalarVariable(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result.To<uint32_t>(), 20);
		result = ScalarVariable(static_cast<uint32_t>(10)) + ScalarVariable(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result.To<uint32_t>(), 20);
		result = ScalarVariable(static_cast<uint32_t>(10)) + ScalarVariable(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result.To<uint32_t>(), 20);
		result = ScalarVariable(static_cast<uint32_t>(10)) + ScalarVariable(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result.To<uint32_t>(), 20);
		result = ScalarVariable(static_cast<uint32_t>(10)) + ScalarVariable(static_cast<int8_t>(-20));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -10);
		result = ScalarVariable(static_cast<uint32_t>(10)) + ScalarVariable(static_cast<int16_t>(-20));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -10);
		result = ScalarVariable(static_cast<uint32_t>(10)) + ScalarVariable(static_cast<int32_t>(-20));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -10);
		result = ScalarVariable(static_cast<uint32_t>(10)) + ScalarVariable(static_cast<int64_t>(-20));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -10);
		result = ScalarVariable(static_cast<uint32_t>(10)) + ScalarVariable(static_cast<int64_t>(-139));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -129);
		result = ScalarVariable(static_cast<uint32_t>(10)) + ScalarVariable(static_cast<int64_t>(-32779));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -32769);
		result = ScalarVariable(static_cast<uint32_t>(10)) + ScalarVariable(-static_cast<int64_t>(2147483659));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -static_cast<int64_t>(2147483649));
		result = ScalarVariable(static_cast<uint32_t>(10)) + ScalarVariable(static_cast<uint8_t>(250));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result.To<uint32_t>(), 260);
		result = ScalarVariable(static_cast<uint32_t>(10)) + ScalarVariable(static_cast<uint16_t>(65534));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result.To<uint32_t>(), 65544);
		result = ScalarVariable(static_cast<uint32_t>(10)) + ScalarVariable(static_cast<uint32_t>(4294967294));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result.To<uint64_t>(), 4294967304);
		result = ScalarVariable(static_cast<uint32_t>(10)) + ScalarVariable(static_cast<float>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = ScalarVariable(static_cast<uint32_t>(10)) + ScalarVariable(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		result = ScalarVariable(static_cast<uint32_t>(10)) + ScalarVariable::FromTick(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, TICK);
		ASSERT_EQ(result.To<uint32_t>(), 20);
		
		result = ScalarVariable(static_cast<uint64_t>(10)) + ScalarVariable(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result.To<uint64_t>(), 20);
		result = ScalarVariable(static_cast<uint64_t>(10)) + ScalarVariable(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result.To<uint64_t>(), 20);
		result = ScalarVariable(static_cast<uint64_t>(10)) + ScalarVariable(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result.To<uint64_t>(), 20);
		result = ScalarVariable(static_cast<uint64_t>(10)) + ScalarVariable(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result.To<uint64_t>(), 20);
		result = ScalarVariable(static_cast<uint64_t>(10)) + ScalarVariable(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result.To<uint64_t>(), 20);
		result = ScalarVariable(static_cast<uint64_t>(10)) + ScalarVariable(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result.To<uint64_t>(), 20);
		result = ScalarVariable(static_cast<uint64_t>(10)) + ScalarVariable(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result.To<uint64_t>(), 20);
		result = ScalarVariable(static_cast<uint64_t>(10)) + ScalarVariable(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result.To<uint64_t>(), 20);
		result = ScalarVariable(static_cast<uint64_t>(10)) + ScalarVariable(static_cast<int8_t>(-20));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -10);
		result = ScalarVariable(static_cast<uint64_t>(10)) + ScalarVariable(static_cast<int16_t>(-20));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -10);
		result = ScalarVariable(static_cast<uint64_t>(10)) + ScalarVariable(static_cast<int32_t>(-20));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -10);
		result = ScalarVariable(static_cast<uint64_t>(10)) + ScalarVariable(static_cast<int64_t>(-20));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -10);
		result = ScalarVariable(static_cast<uint64_t>(10)) + ScalarVariable(static_cast<int64_t>(-139));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -129);
		result = ScalarVariable(static_cast<uint64_t>(10)) + ScalarVariable(static_cast<int64_t>(-32779));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -32769);
		result = ScalarVariable(static_cast<uint64_t>(10)) + ScalarVariable(-static_cast<int64_t>(2147483659));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -static_cast<int64_t>(2147483649));
		result = ScalarVariable(static_cast<uint64_t>(10)) + ScalarVariable(static_cast<uint8_t>(250));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result.To<uint64_t>(), 260);
		result = ScalarVariable(static_cast<uint64_t>(10)) + ScalarVariable(static_cast<uint16_t>(65534));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result.To<uint64_t>(), 65544);
		result = ScalarVariable(static_cast<uint64_t>(10)) + ScalarVariable(static_cast<uint32_t>(4294967294));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result.To<uint64_t>(), 4294967304);
		result = ScalarVariable(static_cast<uint64_t>(10)) + ScalarVariable(static_cast<float>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = ScalarVariable(static_cast<uint64_t>(10)) + ScalarVariable(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		result = ScalarVariable(static_cast<uint64_t>(10)) + ScalarVariable::FromTick(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, TICK);
		ASSERT_EQ(result.To<uint32_t>(), 20);
		
		result = ScalarVariable(static_cast<int8_t>(10)) + ScalarVariable(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), 20);
		result = ScalarVariable(static_cast<int8_t>(10)) + ScalarVariable(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), 20);
		result = ScalarVariable(static_cast<int8_t>(10)) + ScalarVariable(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), 20);
		result = ScalarVariable(static_cast<int8_t>(10)) + ScalarVariable(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), 20);
		result = ScalarVariable(static_cast<int8_t>(10)) + ScalarVariable(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), 20);
		result = ScalarVariable(static_cast<int8_t>(10)) + ScalarVariable(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), 20);
		result = ScalarVariable(static_cast<int8_t>(10)) + ScalarVariable(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), 20);
		result = ScalarVariable(static_cast<int8_t>(10)) + ScalarVariable(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), 20);
		result = ScalarVariable(static_cast<int8_t>(10)) + ScalarVariable(static_cast<int8_t>(-20));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), -10);
		result = ScalarVariable(static_cast<int8_t>(10)) + ScalarVariable(static_cast<int16_t>(-20));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), -10);
		result = ScalarVariable(static_cast<int8_t>(10)) + ScalarVariable(static_cast<int32_t>(-20));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), -10);
		result = ScalarVariable(static_cast<int8_t>(10)) + ScalarVariable(static_cast<int64_t>(-20));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), -10);
		result = ScalarVariable(static_cast<int8_t>(10)) + ScalarVariable(static_cast<int64_t>(-139));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), -129);
		result = ScalarVariable(static_cast<int8_t>(10)) + ScalarVariable(static_cast<int64_t>(-32779));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -32769);
		result = ScalarVariable(static_cast<int8_t>(10)) + ScalarVariable(-static_cast<int64_t>(2147483659));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -static_cast<int64_t>(2147483649));
		result = ScalarVariable(static_cast<int8_t>(10)) + ScalarVariable(static_cast<uint8_t>(128));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), 138);
		result = ScalarVariable(static_cast<int8_t>(10)) + ScalarVariable(static_cast<uint16_t>(32768));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), 32778);
		result = ScalarVariable(static_cast<int8_t>(10)) + ScalarVariable(static_cast<uint32_t>(2147483648));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), 2147483658);
		result = ScalarVariable(static_cast<int8_t>(10)) + ScalarVariable(static_cast<float>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = ScalarVariable(static_cast<int8_t>(10)) + ScalarVariable(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		result = ScalarVariable(static_cast<int8_t>(10)) + ScalarVariable::FromTick(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, TICK);
		ASSERT_EQ(result.To<uint32_t>(), 20);
		
		result = ScalarVariable(static_cast<int16_t>(10)) + ScalarVariable(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), 20);
		result = ScalarVariable(static_cast<int16_t>(10)) + ScalarVariable(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), 20);
		result = ScalarVariable(static_cast<int16_t>(10)) + ScalarVariable(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), 20);
		result = ScalarVariable(static_cast<int16_t>(10)) + ScalarVariable(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), 20);
		result = ScalarVariable(static_cast<int16_t>(10)) + ScalarVariable(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), 20);
		result = ScalarVariable(static_cast<int16_t>(10)) + ScalarVariable(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), 20);
		result = ScalarVariable(static_cast<int16_t>(10)) + ScalarVariable(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), 20);
		result = ScalarVariable(static_cast<int16_t>(10)) + ScalarVariable(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), 20);
		result = ScalarVariable(static_cast<int16_t>(10)) + ScalarVariable(static_cast<int8_t>(-20));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), -10);
		result = ScalarVariable(static_cast<int16_t>(10)) + ScalarVariable(static_cast<int16_t>(-20));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), -10);
		result = ScalarVariable(static_cast<int16_t>(10)) + ScalarVariable(static_cast<int32_t>(-20));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), -10);
		result = ScalarVariable(static_cast<int16_t>(10)) + ScalarVariable(static_cast<int64_t>(-20));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), -10);
		result = ScalarVariable(static_cast<int16_t>(10)) + ScalarVariable(static_cast<int64_t>(-139));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), -129);
		result = ScalarVariable(static_cast<int16_t>(10)) + ScalarVariable(static_cast<int64_t>(-32779));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -32769);
		result = ScalarVariable(static_cast<int16_t>(10)) + ScalarVariable(-static_cast<int64_t>(2147483659));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -static_cast<int64_t>(2147483649));
		result = ScalarVariable(static_cast<int16_t>(10)) + ScalarVariable(static_cast<uint8_t>(128));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), 138);
		result = ScalarVariable(static_cast<int16_t>(10)) + ScalarVariable(static_cast<uint16_t>(32768));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), 32778);
		result = ScalarVariable(static_cast<int16_t>(10)) + ScalarVariable(static_cast<uint32_t>(2147483648));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), 2147483658);
		result = ScalarVariable(static_cast<int16_t>(10)) + ScalarVariable(static_cast<float>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = ScalarVariable(static_cast<int16_t>(10)) + ScalarVariable(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		result = ScalarVariable(static_cast<int16_t>(10)) + ScalarVariable::FromTick(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, TICK);
		ASSERT_EQ(result.To<uint32_t>(), 20);
		
		result = ScalarVariable(static_cast<int32_t>(10)) + ScalarVariable(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), 20);
		result = ScalarVariable(static_cast<int32_t>(10)) + ScalarVariable(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), 20);
		result = ScalarVariable(static_cast<int32_t>(10)) + ScalarVariable(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), 20);
		result = ScalarVariable(static_cast<int32_t>(10)) + ScalarVariable(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), 20);
		result = ScalarVariable(static_cast<int32_t>(10)) + ScalarVariable(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), 20);
		result = ScalarVariable(static_cast<int32_t>(10)) + ScalarVariable(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), 20);
		result = ScalarVariable(static_cast<int32_t>(10)) + ScalarVariable(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), 20);
		result = ScalarVariable(static_cast<int32_t>(10)) + ScalarVariable(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), 20);
		result = ScalarVariable(static_cast<int32_t>(10)) + ScalarVariable(static_cast<int8_t>(-20));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -10);
		result = ScalarVariable(static_cast<int32_t>(10)) + ScalarVariable(static_cast<int16_t>(-20));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -10);
		result = ScalarVariable(static_cast<int32_t>(10)) + ScalarVariable(static_cast<int32_t>(-20));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -10);
		result = ScalarVariable(static_cast<int32_t>(10)) + ScalarVariable(static_cast<int64_t>(-20));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -10);
		result = ScalarVariable(static_cast<int32_t>(10)) + ScalarVariable(static_cast<int64_t>(-139));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -129);
		result = ScalarVariable(static_cast<int32_t>(10)) + ScalarVariable(static_cast<int64_t>(-32779));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -32769);
		result = ScalarVariable(static_cast<int32_t>(10)) + ScalarVariable(-static_cast<int64_t>(2147483659));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -static_cast<int64_t>(2147483649));
		result = ScalarVariable(static_cast<int32_t>(10)) + ScalarVariable(static_cast<uint8_t>(128));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), 138);
		result = ScalarVariable(static_cast<int32_t>(10)) + ScalarVariable(static_cast<uint16_t>(32768));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), 32778);
		result = ScalarVariable(static_cast<int32_t>(10)) + ScalarVariable(static_cast<uint32_t>(2147483648));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), 2147483658);
		result = ScalarVariable(static_cast<int32_t>(10)) + ScalarVariable(static_cast<float>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = ScalarVariable(static_cast<int32_t>(10)) + ScalarVariable(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		result = ScalarVariable(static_cast<int32_t>(10)) + ScalarVariable::FromTick(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, TICK);
		ASSERT_EQ(result.To<uint32_t>(), 20);
		
		result = ScalarVariable(static_cast<int64_t>(10)) + ScalarVariable(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), 20);
		result = ScalarVariable(static_cast<int64_t>(10)) + ScalarVariable(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), 20);
		result = ScalarVariable(static_cast<int64_t>(10)) + ScalarVariable(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), 20);
		result = ScalarVariable(static_cast<int64_t>(10)) + ScalarVariable(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), 20);
		result = ScalarVariable(static_cast<int64_t>(10)) + ScalarVariable(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), 20);
		result = ScalarVariable(static_cast<int64_t>(10)) + ScalarVariable(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), 20);
		result = ScalarVariable(static_cast<int64_t>(10)) + ScalarVariable(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), 20);
		result = ScalarVariable(static_cast<int64_t>(10)) + ScalarVariable(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), 20);
		result = ScalarVariable(static_cast<int64_t>(10)) + ScalarVariable(static_cast<int8_t>(-20));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -10);
		result = ScalarVariable(static_cast<int64_t>(10)) + ScalarVariable(static_cast<int16_t>(-20));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -10);
		result = ScalarVariable(static_cast<int64_t>(10)) + ScalarVariable(static_cast<int32_t>(-20));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -10);
		result = ScalarVariable(static_cast<int64_t>(10)) + ScalarVariable(static_cast<int64_t>(-20));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -10);
		result = ScalarVariable(static_cast<int64_t>(10)) + ScalarVariable(static_cast<int64_t>(-139));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -129);
		result = ScalarVariable(static_cast<int64_t>(10)) + ScalarVariable(static_cast<int64_t>(-32779));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -32769);
		result = ScalarVariable(static_cast<int64_t>(10)) + ScalarVariable(-static_cast<int64_t>(2147483659));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -static_cast<int64_t>(2147483649));
		result = ScalarVariable(static_cast<int64_t>(10)) + ScalarVariable(static_cast<uint8_t>(128));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), 138);
		result = ScalarVariable(static_cast<int64_t>(10)) + ScalarVariable(static_cast<uint16_t>(32768));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), 32778);
		result = ScalarVariable(static_cast<int64_t>(10)) + ScalarVariable(static_cast<uint32_t>(2147483648));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), 2147483658);
		result = ScalarVariable(static_cast<int64_t>(10)) + ScalarVariable(static_cast<float>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = ScalarVariable(static_cast<int64_t>(10)) + ScalarVariable(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		result = ScalarVariable(static_cast<int64_t>(10)) + ScalarVariable::FromTick(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, TICK);
		ASSERT_EQ(result.To<uint32_t>(), 20);
		
		result = ScalarVariable(static_cast<float>(10)) + ScalarVariable(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = ScalarVariable(static_cast<float>(10)) + ScalarVariable(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = ScalarVariable(static_cast<float>(10)) + ScalarVariable(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = ScalarVariable(static_cast<float>(10)) + ScalarVariable(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = ScalarVariable(static_cast<float>(10)) + ScalarVariable(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = ScalarVariable(static_cast<float>(10)) + ScalarVariable(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = ScalarVariable(static_cast<float>(10)) + ScalarVariable(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = ScalarVariable(static_cast<float>(10)) + ScalarVariable(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = ScalarVariable(static_cast<float>(10)) + ScalarVariable(static_cast<float>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = ScalarVariable(static_cast<float>(10)) + ScalarVariable(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		
		result = ScalarVariable(static_cast<double>(10)) + ScalarVariable(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		result = ScalarVariable(static_cast<double>(10)) + ScalarVariable(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		result = ScalarVariable(static_cast<double>(10)) + ScalarVariable(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		result = ScalarVariable(static_cast<double>(10)) + ScalarVariable(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		result = ScalarVariable(static_cast<double>(10)) + ScalarVariable(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		result = ScalarVariable(static_cast<double>(10)) + ScalarVariable(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		result = ScalarVariable(static_cast<double>(10)) + ScalarVariable(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		result = ScalarVariable(static_cast<double>(10)) + ScalarVariable(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		result = ScalarVariable(static_cast<double>(10)) + ScalarVariable(static_cast<float>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		result = ScalarVariable(static_cast<float>(10)) + ScalarVariable(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
	}

	TEST(ScalarVariableTests, WhenSubtactingScalar_ThenCorrectValueReturned)
	{
		ScalarVariable result;
		
		result = ScalarVariable(static_cast<uint8_t>(10)) - ScalarVariable(static_cast<uint8_t>(5));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result.To<uint8_t>(), 5);

		result = ScalarVariable(static_cast<uint8_t>(10)) - ScalarVariable(static_cast<uint8_t>(15));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), -5);
	}

	TEST(ScalarVariableTests, WhenMultiplyingScalar_ThenCorrectValueReturned)
	{
		ScalarVariable result;
		
		result = ScalarVariable(static_cast<uint8_t>(10)) * ScalarVariable(static_cast<uint8_t>(5));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result.To<uint8_t>(), 50);

		result = ScalarVariable(static_cast<uint8_t>(10)) * ScalarVariable(static_cast<int8_t>(-15));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), -150);
	}

	TEST(ScalarVariableTests, WhenDividingScalar_ThenCorrectValueReturned)
	{
		ScalarVariable result;
		
		result = ScalarVariable(static_cast<uint8_t>(10)) / ScalarVariable(static_cast<uint8_t>(5));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result.To<uint8_t>(), 2);

		result = ScalarVariable(static_cast<uint16_t>(150)) / ScalarVariable(static_cast<int8_t>(-15));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), -10);
	}
}
