#include "Service/ServiceBuilder.h"

#ifndef VARIABLEBUSSERVICEBUILDEREGISTER_H
#define VARIABLEBUSSERVICEBUILDEREGISTER_H

#define BUILDER_BOOLEANVARIABLESERVICE_STATIC 							6101
#define BUILDER_BOOLEANVARIABLESERVICE_INPUT 							6102
#define BUILDER_FLOATVARIABLESERVICE_STATIC 							6201
#define BUILDER_FLOATVARIABLESERVICE_INPUT 								6202
#define BUILDER_FLOATVARIABLESERVICE_DEGREE2POLYNOMIALTRANSLATION 		6212
#define BUILDER_FLOATVARIABLESERVICE_DEGREE3POLYNOMIALTRANSLATION 		6213
#define BUILDER_FLOATVARIABLESERVICE_DEGREE4POLYNOMIALTRANSLATION 		6214
#define BUILDER_FLOATVARIABLESERVICE_DEGREE5POLYNOMIALTRANSLATION 		6215
#define BUILDER_FLOATVARIABLESERVICE_DEGREE6POLYNOMIALTRANSLATION 		6216
#define BUILDER_FLOATVARIABLESERVICE_DEGREE7POLYNOMIALTRANSLATION 		6217
#define BUILDER_FLOATVARIABLESERVICE_DEGREE8POLYNOMIALTRANSLATION 		6218
#define BUILDER_FLOATVARIABLESERVICE_DEGREE9POLYNOMIALTRANSLATION 		6219
#define BUILDER_FLOATVARIABLESERVICE_UINT8_LOOKUPTABLETRANSLATION 		6220
#define BUILDER_FLOATVARIABLESERVICE_UINT16_LOOKUPTABLETRANSLATION 		6221
#define BUILDER_FLOATVARIABLESERVICE_UINT32_LOOKUPTABLETRANSLATION 		6222
#define BUILDER_FLOATVARIABLESERVICE_UINT64_LOOKUPTABLETRANSLATION 		6223
#define BUILDER_FLOATVARIABLESERVICE_INT8_LOOKUPTABLETRANSLATION 		6224
#define BUILDER_FLOATVARIABLESERVICE_INT16_LOOKUPTABLETRANSLATION 		6225
#define BUILDER_FLOATVARIABLESERVICE_INT32_LOOKUPTABLETRANSLATION 		6226
#define BUILDER_FLOATVARIABLESERVICE_INT64_LOOKUPTABLETRANSLATION 		6227
#define BUILDER_FLOATVARIABLESERVICE_FLOAT_LOOKUPTABLETRANSLATION 		6228
#define BUILDER_FLOATVARIABLESERVICE_DOUBLE_LOOKUPTABLETRANSLATION 		6229
#define BUILDER_FLOATVARIABLESERVICE_UINT8_2AXISTABLETRANSLATION 		6230
#define BUILDER_FLOATVARIABLESERVICE_UINT16_2AXISTABLETRANSLATION 		6231
#define BUILDER_FLOATVARIABLESERVICE_UINT32_2AXISTABLETRANSLATION 		6232
#define BUILDER_FLOATVARIABLESERVICE_UINT64_2AXISTABLETRANSLATION 		6233
#define BUILDER_FLOATVARIABLESERVICE_INT8_2AXISTABLETRANSLATION 		6234
#define BUILDER_FLOATVARIABLESERVICE_INT16_2AXISTABLETRANSLATION 		6235
#define BUILDER_FLOATVARIABLESERVICE_INT32_2AXISTABLETRANSLATION 		6236
#define BUILDER_FLOATVARIABLESERVICE_INT64_2AXISTABLETRANSLATION 		6237
#define BUILDER_FLOATVARIABLESERVICE_FLOAT_2AXISTABLETRANSLATION 		6238
#define BUILDER_FLOATVARIABLESERVICE_DOUBLE_2AXISTABLETRANSLATION 		6239
#define VARIABLE_BUS											6001
namespace Service
{
	class VariableBusServiceBuilderRegister
	{
	public:
		static void Register(ServiceBuilder *&serviceBuilder);
	};
}
#endif
